[tools]
"aqua:atuin" = "18.10.0"
"aqua:bat" = "0.26.1"
"aqua:cmake" = "4.2.1"
"aqua:delta" = "0.18.1"
"aqua:fd" = "10.3.0"
"aqua:fzf" = "0.67.0"
"aqua:lua-language-server" = "3.16.4"
"aqua:neovim" = "0.11.5"
"aqua:ripgrep" = "15.1.0"
"aqua:starship" = "1.24.1"
"aqua:uv" = "0.9.18"
"github:clangd/clangd" = "21.1.8"
"github:noborus/ov" = "0.50.2"
"github:rr-debugger/rr" = "5.9.0"
